### ISSUE TITLE
Component is re-rendered before leaving the page

### ISSUE THREAD

**Issue by EgidioCaprino** [illinois/next-page-transitions#23] opened 2019-02-05 17:41 UTC
Hi all :wave: 

I'd love to use this library in my project but I'm having an issue with route changes. When I leave a page that is re-rendered. This throws an error in some cases because the route has changed in the meantime and the component can't find some route parameters.

Let me give you an example.

- I'm in the index `/`
- I navigate to `/category?id=6` which renders `category.js` page
- I navigate back to `/`
- the URL changes from `/category?id=6` to `/`
- before leaving `category.js` the component is re-rendered. Since the `category.js` page relies on the `id` parameter an error is thrown

Am I doing something wrong here?

**Comment by nwalters512** [comment] 2019-02-05 17:49
I haven't used this library with a page that uses route parameters. Can you put together a small app that reproduces the error you're seeing?

**Comment by EgidioCaprino** [comment] 2019-02-05 19:10
I can't reproduce it on a [Next.js vanilla project](https://repl.it/@EgidioCaprino1/CraftyClientsideConference). Could it be related to `<ApolloProvider>`? I pushed the changes with the problem on [this branch](https://github.com/EgidioCaprino/youvector/blob/next-page-transitions/website/pages/_app.js).

**Comment by nwalters512** [comment] 2019-03-13 20:44
That's certainly possible. I'm not familiar with Apollo. If you can put together a small self-contained example (Codesandbox would be great), I'd be happy to look into this more. Until then, I'm going to close this out for now. It's possible that this will be fixed in an upcoming v1.0.0 release as well.

**Closed by nwalters512** 2019-03-13 20:44 UTC

**Comment by Solitaryo** [comment] 2019-04-12 10:30
I have the same problem, I'm using Apollo and a url with query params, every time I go back from a URL with query params, the animation doesn't work, it first load the page and then it does the animation, like re rendering the component first and then using the animation. But this only happens when you have URL params, which is weird. Any idea how to force the animation?

**Comment by tm1000** [comment] 2019-07-17 17:34
Same issue as well and also using Apollo.

**Comment by NamPNQ** [comment] 2019-10-17 15:42
This happened with simple example in the `examples` folder

**Comment by nwalters512** [comment] 2019-10-17 15:46
@NamPNQ could you describe the exact error you saw and how to reproduce it? Which example was this with?

**Comment by NamPNQ** [comment] 2019-10-17 16:55
@nwalters512  You can test with #47

**Comment by h0gar** [comment] 2019-11-27 16:29
Anyone found a temporary fix or an alternative with next.js and apollo?

**Comment by NamPNQ** [comment] 2019-11-28 10:03
@h0gar you can try my fix in #47

**Comment by h0gar** [comment] 2019-11-28 11:33
@NamPNQ React.memo (I have func components) doesn't change anything in my case.. :/

**Comment by NamPNQ** [comment] 2019-11-28 19:12
> @NamPNQ React.memo (I have func components) doesn't change anything in my case.. :/

I mean change the file `src/PageTransition.js`, not React.memo

**Comment by Bleuzen** [comment] 2020-07-12 16:00
Also happens with framer-motion. The problem seems to be that next router already changes the route and query parameters before the exit animation finished.

So the old page gets the query parameters of the new route it is transitioning to.

Example:

If you use the state to get the query parameters:
```javascript
  const router = useRouter()
  const { id } = router.query
```

the id parameter first is the id parameter passed to this page. But when you click on a link, next already changed the route and query parameters to the new page. So the id parameter becomes undefined, if the new route it is transitioning to does not have an id parameter. And since this is a state change, the old page which is fading out is now re-rendered with the new id parameter of the new route (which is undefined in this example).

Somehow next router route and query changes have to be delayed until the exit animation is done.

One workaround for now is to check the pathname before setting the id (and other query parameters you use) so that the old route doesn't get the parameters of the new route.
This may look something like this:

```javascript
let id

export default function Category() {
  const router = useRouter()

  if (router.pathname === '/category') {
    id = router.query.id
  }

...
}
```
