### ISSUE TITLE
Error when running on production env

### ISSUE THREAD

**Issue by freddygymlib** [illinois/next-page-transitions#17] opened 2019-01-20 20:41 UTC
Hello,

running the example `https://github.com/zeit/next.js/tree/master/examples/with-next-page-transitions` on production env triggers an error:

> TypeError: Cannot read property 'isRequired' of null
    at Object.<anonymous> (/home/freddy/Workspace/workspace-projects/workspace-together/with-next-page-transitions/node_modules/next-page-transitions/lib/PageTransition.js:300:37)

Which refers to this:  line 300 - PageTransition.js
`timeout: _PropTypes.timeoutsShape.isRequired,`

When looking from the origin of the problem, I found this line on the react-transition-group dependency

`var timeoutsShape = process.env.NODE_ENV !== 'production' ? _propTypes.default.oneOfType([_propTypes.default.number, _propTypes.default.shape({
  enter: _propTypes.default.number,
  exit: _propTypes.default.number
}).isRequired]) : null;`

Note: this problems does not appear on the 1.0.0-alpha.1 release because back then we had on PageTransition.js:

`timeout: _PropTypes.timeoutsShape`

Regards,

Freddy

**Comment by freddygymlib** [comment] 2019-01-22 09:36
Hello, 

Becareful, I think there is a small typo in the pull request #18 

code removed:  `loadingCallbackName: 'pageTransitionReadyToEnter',`
new code: 	  `loadingCallbackName: 'pagessTransitionReadyToEnter',`

Regards,

Freddy

**Comment by teleginzhenya** [comment] 2019-01-22 09:47
@freddygymlib thanks will fix it, it is all about MacBook Pro 2017 keyboard :(

**Comment by nwalters512** [comment] 2019-01-22 21:55
Looks like this was caused by https://github.com/reactjs/react-transition-group/pull/448. Will take a look at the PR!

**Comment by ScottMorse** [comment] 2019-01-29 02:02
I just ran into this for the first time as well today.  Yeah, the problem is that the `react-transition-group`'s custom PropTypes (`timeoutsShape` and `classNamesShape`) return null if the NODE_ENV is set to "production."

Editing the source in node_modules was an alright fix in development, but to remedy this when having Heroku build my app remotely, I had to copy the source code into custom files to be able to import the corrected code.

I love the package for page transitions.  It just needs an update which either does away with the `.isRequired`s on those special PropTypes or detects the NODE_ENV similarly to `react-transition-group` in order to dynamically deal with this problem.

**Comment by vincivince** [comment] 2019-01-29 14:40
Hi all, any moves to deploy a fix ?
Thx

**Comment by ScottMorse** [comment] 2019-01-29 16:40
I made a pull request #21 using the fix I used most recently with an app I deployed.  Right now I have to use my custom copy of the source in my project since the Node packages are installed and built remotely.

It allows for the `timeout` and `loadingTimeout`'s prop types (the react-transition-group's custom `timeoutsShape` type) to still be required in development, but avoids these errors seen in production. 

Let me know if it seems like the fix you are looking for.

**Comment by genox** [comment] 2019-01-30 14:22
@ScottMorse thanks, gonna use your fork meanwhile 👍

**Comment by nwalters512** [comment] 2019-01-30 20:51
Resolved by the PR from @ScottMorse in #21 - I'll release a version containing the fix shortly.

**Closed by nwalters512** 2019-01-30 20:51 UTC

**Comment by fr3fou** [comment] 2019-02-01 15:25
So can it now be used in production?

**Comment by ScottMorse** [comment] 2019-02-01 15:54
I am using it now in my Next app in production and it's working! https://www.pymusician.com
